### ISSUE TITLE
Shelly Device Handler don't return status

### ISSUE THREAD

**Issue by joinwind** [sgrayban/SmartThings#1]
The Handler work's great, but the "status" don't work.

**Comment by sgrayban** [comment]
Ok I'll have another look at it.

**Comment by joinwind** [comment]
Thanks

**Comment by jrm523** [comment]
Thanks

On Tue, Aug 6, 2019, 2:57 AM joinwind <notifications@github.com> wrote:

 I recently noticed mine wasnt working properly either. Thank you for
creating it and I appreciate you taking a look at fixing it. Eventually ill
make the move to Hubitat.

**Comment by joinwind** [comment]
Hello, i can read the status (i don't insert the correct device id, but for shelly 2? , i've to put the same hex address to the two lights, and smartthings don't want but in live log i see the same address. any idea?

**Comment by sgrayban** [comment]
@joinwind are you saying you are attempting to install it twice for 2 relay switches ?

As for the status update just create a poll request via webcore to poll every minute.

I really have moved away from SmartThings and use Hubitat these days. SmartThings became a disappointment to me. It isn't what it started out in the early years of me using it. When Samsung bought it they turned it into shit.

**Comment by joinwind** [comment]
in shelly 2 i have two device (id0 & id1) , but the hex code are the same and i can't put the same device id . thanks for your help i see hubitat but there is not sell in EU. Regards

**Comment by sgrayban** [comment]
Hubitat is SOLD in the EU... tons of users in UK and Germany use it. Also sell in  Australia and New Zeland now. Whoever told they don't is lying to you.

**Comment by joinwind** [comment]
oh.. my mistake sorry

**Comment by sgrayban** [comment]
Well I can't even get my handler to even work in smartthings any more. I think I'm just going to abandoned my smartthings DHT's since I dont use ST anymore.

Sorry guys. You are welcomed to bang on the code your self.

**Comment by jrm523** [comment]
Scott,

I feel your frustration with smart things. Im blown away of how big of a
mess they have made it (two apps with different functionality). What is
your thoughts on Home Assistant?

**Comment by sgrayban** [comment]
I just started to fool around with HA using their hassbian image and it's not for the weak hearted user. Nearly nothing is automatic like ST or HE. It's all manual for the most part.

The Hass.io version is better but not by much. It's very restrictive and you can't run normal raspbian programs which is a deal breaker for me. Using docker.io is a pain in the ass for Hass.io I spent hours attempting to install it as a docker image and got no place.

ST for the first 2-3 years was a pleasure until it was sold.

I highly suggest HE if you don't want to deal with manual installs in HA. BTW HA version of rules is the pits.

**Comment by sgrayban** [comment]
I am only using HA because I wanted automations for Raincloud which HA does support and not available in ST or HE.
